[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [".bridgetown-cache", ".bridgetown-webpack", "output"]

[build]
  command = "yarn deploy && ./bin/netlify.sh"
  publish = "output"

[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true


[[headers]]
  for = "*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
      object-src  'none';
      worker-src  'none';
      block-all-mixed-content;
      upgrade-insecure-requests;'''
    Strict-Transport-Security = "max-age=15552000; includeSubDomains"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cache-Control = "public, max-age=604800, s-max-age=604800"
    Permissions-Policy = "interest-cohort=()"

[[headers]]
  for = "/"
  [headers.values]
    Link = [
      "<CSS_PATH>; rel=preload; as=style",
      "<https://NETLIFY_IMAGES_CDN_DOMAIN>; rel=dns-prefetch"
    ]

[[headers]]
  for = "/*.(png|jpg|js|css|svg|woff|ttf|eot|ico|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-max-age=31536000"
